require 'user.launch'
require 'user.core.options'
require 'user.core.keymaps'
require 'user.core.autocmds.noplugins'
require 'user.core.statusline'
require 'user.lazy'
require 'user.core.autocmds.plugins'
