require 'gmr.launch'
require 'gmr.core.options'
require 'gmr.core.keymaps'
require 'gmr.core.autocmds.noplugins'
require 'gmr.core.statusline'
require 'gmr.lazy'
require 'gmr.core.autocmds.plugins'
require 'gmr.core.winbar'
