return {
  "bash-language-server",
  "buf",
  "buf-language-server",
  -- "chrome-debug-adapter",
  "clangd",
  "codelldb",
  "cpptools",
  "css-lsp",
  "debugpy",
  "delve",
  "deno",
  "dockerfile-language-server",
  "emmet-ls",
  "eslint-lsp",
  -- "firefox-debug-adapter",
  "go-debug-adapter",
  "golangci-lint",
  "gopls",
  "html-lsp",
  -- "intelephense",
  "isort",
  "java-debug-adapter",
  "java-test",
  "jdtls",
  -- "js-debug-adapter",
  "json-lsp",
  -- "kotlin-language-server",
  "lua-language-server",
  -- "netcoredbg",
  -- "nimlangserver",
  -- "node-debug2-adapter",
  "omnisharp",
  "prettier",
  "pylint",
  "pyright",
  "rubocop",
  -- "ruff-lsp",
  "rust-analyzer",
  "sqlls",
  "stylua",
  "svelte-language-server",
  "tailwindcss-language-server",
  "taplo",
  "typescript-language-server",
  -- "vim-language-server",
  "yaml-language-server",
}
