local M = {}

local utils = require("config.utils")

local list = {
    -- "ada",
    -- "agda",
    -- "arduino",
    "astro",
    -- "awk",
    "bash",
    -- "bass",
    -- "beancount",
    -- "bibtex",
    -- "blueprint",
    "c",
    "c_sharp",
    -- "cairo",
    -- "capnp",
    -- "chatito",
    -- "clojure",
    "cmake",
    "comment",
    -- "commonlisp",
    -- "cooklang",
    -- "corn",
    -- "cpon",
    "cpp",
    "css",
    "csv",
    -- "cuda",
    -- "cue",
    -- "d",
    "dart",
    -- "devicetree",
    -- "dhall",
    "diff",
    "dockerfile",
    -- "dot",
    -- "dtd",
    -- "ebnf",
    -- "eex",
    "elixir",
    -- "elm",
    -- "elsa",
    -- "elvish",
    -- "embedded_template",
    -- "erlang",
    -- "fennel",
    -- "firrtl",
    -- "fish",
    -- "foam",
    -- "forth",
    -- "fortran",
    -- "fsh",
    -- "func",
    -- "fusion",
    -- "gdscript",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    -- "gleam",
    -- "glimmer",
    -- "glsl",
    "go",
    -- "godot_resource",
    "gomod",
    "gosum",
    "gowork",
    "graphql",
    -- "hack",
    -- "hare",
    -- "haskell",
    -- "haskell_persistent",
    -- "hcl",
    -- "heex",
    -- "hjson",
    -- "hlsl",
    -- "hocon",
    -- "hoon",
    "html",
    "htmldjango",
    -- "http",
    -- "hurl",
    -- "ini",
    -- "ispc",
    -- "janet_simple",
    "java",
    "javascript",
    -- "jq",
    "jsdoc",
    "json",
    -- "json5",
    "jsonc",
    -- "jsonnet",
    -- "julia",
    "kdl",
    "kotlin",
    -- "lalrpop",
    "latex",
    -- "ledger",
    -- "llvm",
    "lua",
    "luadoc",
    "luap",
    "luau",
    -- "m68k",
    "make",
    "markdown",
    "markdown_inline",
    -- "matlab",
    -- "menhir",
    -- "mermaid",
    "meson",
    -- "mlir",
    -- "nickel",
    "ninja",
    "nix",
    -- "norg",
    -- "objc",
    "ocaml",
    "ocaml_interface",
    "ocamllex",
    -- "odin",
    -- "org",
    -- "pascal",
    -- "passwd",
    -- "pem",
    -- "perl",
    "php",
    "phpdoc",
    -- "pioasm",
    -- "po",
    -- "poe_filter",
    "prisma",
    -- "promql",
    "proto",
    -- "prql",
    -- "psv",
    "pug",
    -- "puppet",
    "pymanifest",
    "python",
    -- "ql",
    -- "qmldir",
    -- "qmljs",
    "query",
    -- "r",
    -- "racket",
    "rasi",
    -- "re2c",
    "regex",
    -- "rego",
    "requirements",
    -- "rnoweb",
    -- "robot",
    -- "ron",
    -- "rst",
    "ruby",
    "rust",
    -- "scala",
    "scheme",
    "scss",
    -- "slint",
    -- "smali",
    -- "smithy",
    -- "solidity",
    -- "sparql",
    "sql",
    -- "squirrel",
    -- "starlark",
    -- "strace",
    -- "supercollider",
    -- "surface",
    "svelte",
    -- "swift",
    -- "sxhkdrc",
    -- "systemtap",
    -- "t32",
    -- "tablegen",
    -- "teal",
    -- "terraform",
    -- "thrift",
    -- "tiger",
    -- "tlaplus",
    -- "todotxt",
    "toml",
    -- "tsv",
    "tsx",
    -- "turtle",
    -- "twig",
    "typescript",
    -- "ungrammar",
    -- "usd",
    -- "uxntal",
    -- "v",
    -- "vala",
    -- "verilog",
    -- "vhs",
    "vim",
    "vimdoc",
    "vue",
    -- "wgsl",
    -- "wgsl_bevy",
    -- "wing",
    "xml",
    "yaml",
    -- "yang",
    -- "yuck",
    "zig",
}

function M.install_automatically()
    if vim.fn.has("win32") == 1 or utils.running_wsl() or utils.running_android() then
        return {}
    end

    return list
end

return M
