local M = {}

M.to_setup = {
    'angularls',
    'astro',
    'bashls',
    'biome',
    'bufls',
    'clangd',
    'cssls',
    'denols',
    'dockerls',
    'elixirls',
    'emmet_ls',
    'eslint',
    'gleam',
    'gopls',
    'html',
    'intelephense',
    -- 'jdtls',
    'jsonls',
    'kotlin_language_server',
    'nim_langserver',
    'ocamllsp',
    'omnisharp',
    -- 'pylance',
    -- 'pylyzer',
    'pyright',
    'rust_analyzer',
    'templ',
    -- "solargraph",
    'svelte',
    'lua_ls',
    -- "tailwindcss",
    'taplo',
    'tsserver',
    'vimls',
    'volar',
    'yamlls',
}

return M
